# Makefile
run-dist:
	@./build/install/app/bin/app

build:
	@./gradlew clean build

install:
	@./gradlew clean installDist

test:
	@./gradlew test

report:
	@./gradlew jacocoTestReport


.PHONY: build